# Generated by Django 4.2.17 on 2025-01-04 14:33

import django.core.validators
from django.db import migrations, models
import siweauth.models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answerHash',
            field=models.BinaryField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='bounty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionAddress',
            field=models.CharField(max_length=42, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$'), siweauth.models.validate_ethereum_address], verbose_name='FactHound Question Address'),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionHash',
            field=models.BinaryField(null=True),
        ),
    ]
