# Generated by Django 5.1.4 on 2025-02-05 01:19

import django.core.validators
import siweauth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_answer_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='questionAddress',
        ),
        migrations.AddField(
            model_name='question',
            name='contractAddress',
            field=models.CharField(max_length=42, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$'), siweauth.models.validate_ethereum_address], verbose_name='FactHound Contract Address'),
        ),
    ]
