# Generated by Django 5.1.4 on 2025-02-12 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_answer_confirmed_onchain_question_confirmed_onchain'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='selection_confirmed_onchain',
            field=models.BooleanField(null=True),
        ),
    ]
